### ISSUE TITLE
\E[200~ and \E[201~ sequences

### ISSUE THREAD

**Issue by jwilk** [terminalguide/terminalguide#13]
The sequences <kbd>ESC</kbd>`[200~` and <kbd>ESC</kbd>`[201~` are mentioned on the [Bracketed Paste Mode page](https://terminalguide.namepad.de/mode/p2004/), but they are not in the [Control Characters and Escape Sequences list](https://terminalguide.namepad.de/seq/).

**Comment by textshell** [comment]
Thanks for getting in touch.

Yes, the "Control Characters and Escape Sequences" describe sequences in the application to terminal direction.

The ESC`[200~` and ESC`[201~` are used in terminal to application (input) direction. I've always meant to create a Page for this direction, but work on termpaint and Tui Widgets prevented me from actually getting that done.

I guess it can't hurt for me to check that the page actually reflects the intended communication direction.

Does that answer your question?

**Comment by jwilk** [comment]
Makes sense.
Feel free to close the issue.

**Comment by textshell** [comment]
Well it never actually said that it's only for application to terminal direction. I've opened #14 to fix that.
