### ISSUE TITLE
Add entries for new aliases for XTPUSHSGR and XTPOPSGR

### ISSUE THREAD

**Issue by jazzdelightsme** [terminalguide/terminalguide#3]
In xterm patch [#345](https://invisible-island.net/xterm/xterm.log.html#xterm_345), Thomas added some aliases for `XTPUSHSGR` and `XTPOPSGR`. It doesn't look like he's updated the control sequences page on his website yet, but you can see the change [here](https://github.com/ThomasDickey/xterm-snapshots/commit/753d745c929453a1ff99180353bebf5590db1757#diff-ab6c61d24c6e77692acd0a24c1b01c0e). Summary: the new sequences are CSI+"#p" for push and CSI+"#q" for pop.

**Comment by textshell** [comment]
Thanks for opening this issue. I plan to add these sequence when i together with the other sequences from xterm 345 when i get to review the diff between 344 and 345.

**Comment by textshell** [comment]
Added with todays update.
