### ISSUE TITLE
Add legend for support icons

### ISSUE THREAD

**Issue by xi** [terminalguide/terminalguide#7]
The various table cells are either empty, contain the word "todo" or one of the following icons: ✔, ✓, ☹, ∅, 🔧. I am not entirely sure what each of these icons means so some kind of legend (maybe on the home page) would be appreciated.

**Comment by textshell** [comment]
Yes, that would be useful.

Does the legend in #8 answer your question?

**Comment by xi** [comment]
Yes, that's perfect.

**Comment by teknoraver** [comment]
Hi, what are the circled letters (Ⓝ,Ⓢ,Ⓒ etc.) used for?
Can we document also these?

**Comment by textshell** [comment]
In the future please open new issues instead of reusing an already closed issue. It really helps tracking where something is still open.

I've opened a pull request with an attempt at extending the legend in #19. Let's continue this discussion there.
